"""LLM settings hooks: OpenRouter capability/cost enrichment.

This module is import-safe: it only registers ``@hook`` decorated functions (the
host wires them at runtime); nothing runs at module top level.

There is deliberately NO server-side validation of the chosen ``model``: the admin
UI suggests the catalog ids (UI-only enum), but saving a model id that is not in the
current catalog is allowed (the provider may serve it, the catalog may be stale, or
offline). The hook only ENRICHES the stored settings, best-effort.
"""

from __future__ import annotations

from typing import Any, Dict

from cat import hook
from cat.log import log

from .openrouter import catalog_last_ok, find_model

# Config class name generated by factories._build_openrouter_config. The save path
# (ServiceFactory) matches configs by class name, so this name is stable.
OPENROUTER_CONFIG_NAME = "LLMOpenRouterConfig"

# OpenRouter catalog fields copied into the stored settings (capabilities + costs
# for accounting). Values are either kept as-is or normalized to per-1M USD.
_CATALOG_TO_SETTINGS: Dict[str, str] = {
    "context_length": "max_token_context",
    "max_completion_tokens": "max_completion_tokens",
    "prompt_cost_per_1m": "prompt_cost_per_1m",
    "completion_cost_per_1m": "completion_cost_per_1m",
    "input_cache_read_cost_per_1m": "input_cache_read_cost_per_1m",
    "request_cost": "request_cost",
}


@hook(priority=1)
def before_llm_settings_update(payload: Dict[str, Any], language_model_name: str, cat) -> Dict[str, Any]:
    """Auto-populate the OpenRouter model's capabilities and costs before saving.

    Runs only for the OpenRouter config (``LLMOpenRouterConfig``). When the chosen
    ``model`` is found in the OpenRouter catalog, the stored settings are enriched
    with:

    * ``is_multimodal`` / ``input_modalities`` — for the multimodal pipeline;
    * ``max_token_context`` / ``max_completion_tokens`` — for context-window split;
    * the per-1M-token costs (``prompt_cost_per_1m``, ``completion_cost_per_1m``,
      ``input_cache_read_cost_per_1m``, ``request_cost``) — for accounting.

    Best-effort: if the catalog is unreachable or the model is not in it, the payload
    is saved unchanged (with a warning) — never blocks the user.
    """
    if language_model_name != OPENROUTER_CONFIG_NAME:
        return payload

    model = payload.get("model")
    if not model:
        return payload

    # force=True bypasses the TTL cache: at save time we want the freshest catalog.
    info = find_model(model, force=True)
    if info is None:
        if catalog_last_ok():
            log.warning(
                f"OPENROUTER model '{model}' not found in the catalog: saving without capability/cost enrichment"
            )
        else:
            log.warning(f"OPENROUTER catalog unreachable at save time: saving model '{model}' without enrichment")
        return payload

    # capabilities + costs from the catalog
    for catalog_key, settings_key in _CATALOG_TO_SETTINGS.items():
        if info.get(catalog_key) is not None:
            payload[settings_key] = info[catalog_key]

    modalities = info.get("input_modalities") or []
    payload["is_multimodal"] = "image" in modalities
    payload["input_modalities"] = modalities

    log.info(f"OPENROUTER settings enriched for model '{model}' (multimodal={payload['is_multimodal']})")
    return payload